# Generated by Django 4.2.16 on 2024-09-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='city',
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='authors',
            name='surname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
